#!/bin/sh

PREREQS=""
prereqs()
{
	echo $PREREQS
}


case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

parse_cmdline() {
    for x in $(cat /proc/cmdline); do
        case $x in
            hostname=*)
                HOST="${x#hostname=}"
                echo "export HOST=\"$HOST\"" >> /etc/casper.conf ;;
            userfullname=*)
                USERFULLNAME="${x#userfullname=}"
                echo "export USERFULLNAME=\"$USERFULLNAME\"" >> /etc/casper.conf ;;
            username=*)
                USERNAME="${x#username=}"
                echo "export USERNAME=\"$USERNAME\"" >> /etc/casper.conf ;;
        esac
    done
}

parse_cmdline
