#!/bin/bash
set -e

if [ -f ./common-functions ]; then
    . ./common-functions
else
    . /usr/share/mk-live-recovery/common-functions
fi

export TARGET_DRIVE=${TARGET_DRIVE:-/dev/sdb}
export ROOT_DEVICE=${ROOT_DEVICE:-/dev/sdb1}
export SWAP_DEVICE=${SWAP_DEVICE:-/dev/sdb5}
export MOUNTPOINT=${MOUNTPOINT:-/mnt/sdb1}

unlink_exclude_file () {
    if [ -f "$EXCLUDE_FILE" ]; then
        rm -f "$EXCLUDE_FILE"
    fi
}

mk_exclude_file () {
    EXCLUDE_FILE=${EXCLUDE_FILE:-"$(mktemp)"}
    unshift_trap0_functions unlink_exclude_file
    my_run_parts exclude "$1" | $SUDO_CMD tee "$EXCLUDE_FILE"
}


mirror_data () {
    mk_exclude_file data
    $SUDO_CMD rsync -av --delete -HAX --one-file-system --exclude-from="$EXCLUDE_FILE" "/" "${MOUNTPOINT}/"
}

mirror_full () {
    mk_exclude_file full
    $SUDO_CMD rsync -av --delete -HAX --one-file-system --delete-excluded --exclude-from="$EXCLUDE_FILE" "/" "${MOUNTPOINT}/"
}

mirror_live () {
    $SUDO_CMD rsync -aAHX --one-file-system --progress "${SRC_DIR}/" "${MOUNTPOINT}/"
}

data () {
    mount_target
    my_run_parts pre-mirror data
    mirror_data
    my_run_parts post-mirror data
}

full () {
    unshift_trap0_functions initd_start; initd_stop
    mount_target
    my_run_parts pre-mirror full
    mirror_full
    bind_mount_in_target
    my_run_parts post-mirror full
}

live () {
    unshift_trap0_functions initd_start; initd_stop
    mount_target
    my_run_parts pre-mirror live
    mirror_live
    bind_mount_in_target
    my_run_parts post-mirror live
}

usage () {
    cat <<USAGE
usage: $0 data
usage: $0 full
USAGE
}

if [ "${1:+set}" = set ]; then
    set -x
    "$@"
    gettext 'done.'; echo
else
    usage
    exit 1
fi
