#!/bin/sh

PREREQ=""
DESCRIPTION="maybe_break local..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

maybe_break local

log_end_msg
